name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy-to-aws:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init (bootstrap)
        run: terraform init
        working-directory: infra/bootstrap

      - name: Terraform Validate (bootstrap)
        run: terraform validate
        working-directory: infra/bootstrap

      - name: Terraform Plan (bootstrap)
        run: terraform plan
        working-directory: infra/bootstrap

      - name: Terraform Apply (bootstrap)
        run: terraform apply -auto-approve
        working-directory: infra/bootstrap

      - name: Terraform Init (infra)
        run: terraform init
        working-directory: infra

      - name: Terraform Validate (infra)
        run: terraform validate
        working-directory: infra

      - name: Terraform Plan (infra)
        run: terraform plan
        working-directory: infra

      - name: Terraform Apply (infra)
        run: terraform apply -auto-approve
        working-directory: infra
